# Use Rust docker image, see: https://hub.docker.com/_/rust/
image: rust:latest

variables:
  CARGO_HOME: $CI_PROJECT_DIR/cargo
 
cache:
  key: "$CI_JOB_NAME"
  untracked: true
  paths:
    - cargo/
    - target/

# Defines stages which are to be executed
stages:
  - check
  - release
  - deploy

# Run `cargo test` for the project with stable Rust
run-build:
  stage: check
  before_script:
    - rustup component add clippy
    - cargo install --force cargo-audit
  script:
    - rustc --version && cargo --version
    - cargo test
    - cargo clippy -- --deny warnings
    - cargo audit

release-build:
  stage: release
  script:
    - cargo build --release
  artifacts:
    paths:
      - target/release/mailin-server
  only:
    - master

deploy:
  image: kroniak/ssh-client:3.15
  stage: deploy
  dependencies:
    - release-build
  before_script:
    - eval $(ssh-agent -s)
    - echo "$SSH_DEPLOY_KEY" | ssh-add -
    - apk add tar zstd
  script:
    - >
      SSH_DEPLOY_USER=$SSH_DEPLOY_USER
      SSH_DEPLOY_PORT=$SSH_DEPLOY_PORT
      mailin-server/deploy/deploy.sh
  only:
    - master
